# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"expanding_mean": "expanding.ipynb",
         "expanding_std": "expanding.ipynb",
         "expanding_max": "expanding.ipynb",
         "expanding_min": "expanding.ipynb",
         "rolling_mean": "rolling.ipynb",
         "rolling_std": "rolling.ipynb",
         "rolling_max": "rolling.ipynb",
         "rolling_min": "rolling.ipynb"}

modules = ["expanding.py",
           "rolling.py"]

doc_url = "https://jose-moralez.github.io/window_ops/"

git_url = "https://github.com/jose-moralez/window_ops/tree/master/"

def custom_doc_links(name): return None
