# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"rolling_mean": "00_core.ipynb",
         "rolling_std": "00_core.ipynb",
         "rolling_max": "00_core.ipynb",
         "rolling_min": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://jose-moralez.github.io/window_ops/"

git_url = "https://github.com/jose-moralez/window_ops/tree/master/"

def custom_doc_links(name): return None
