# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/shift.ipynb.

# %% auto 0
__all__ = ['shift_array']

# %% ../nbs/shift.ipynb 2
import numpy as np
from numba import njit  # type: ignore

# %% ../nbs/shift.ipynb 3
@njit
def shift_array(x: np.ndarray, offset: int) -> np.ndarray:
    n_samples = x.size
    out = np.full_like(x, np.nan)
    for i in range(n_samples - offset):
        out[i + offset] = x[i]
    return out
